export { default as XSwitch } from './Switch.vue'
export { default as XButton } from './Button.vue'
export { default as XTabs } from './tabs/Tabs.vue'
export { default as XTab } from './tabs/Tab.vue'
export { default as XDialog } from './Dialog.vue'
export { openDialog as openDialog } from './plugin/openDialog'
