export { default as XSwitch } from './Switch.vue'
export { default as XButton } from './Button.vue'
export { default as XTabs } from './tabs/tabs.vue'
export { default as XTab } from './tabs/tab.vue'
export { default as XDialog } from './Dialog.vue'
export { default as XIcon } from './Icon.vue'
export { openDialog as openDialog } from './plugin/openDialog'
